name: Docker

on:
  push:
    branches: 
      - main
  release:
    types: [published]

env:
  IMAGE_NAME: drupal-qa

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build images
        run: |
          docker build . --tag $IMAGE_NAME:${GITHUB_REF##*/}

      - name: Push images to GitHub Container Registry
        if: ${{ github.event_name == 'release' }}
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo IMAGE_ID=$IMAGE_ID
          docker tag $IMAGE_NAME:${GITHUB_REF##*/} $IMAGE_ID:${GITHUB_REF##*/}
          docker tag $IMAGE_NAME:${GITHUB_REF##*/} $IMAGE_ID:latest
          docker push $IMAGE_ID:${GITHUB_REF##*/}
          docker push $IMAGE_ID:latest
