name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - refs/tags/*

env:
  IMAGE_NAME: drupal-qa
  TAG: ${GITHUB_REF##*/}
jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build images
        run: |
          docker build . --tag $IMAGE_NAME:$TAG

      - name: Push images to GitHub Container Registry
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          # Change all uppercase to lowercase.
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo IMAGE_ID=$IMAGE_ID
          docker tag $IMAGE_NAME:$TAG $IMAGE_ID:$TAG
          docker push $IMAGE_ID:$TAG
